version: "3"

services:
  ejabberd:
    container_name: ejabberd

    # # Local build (from https://github.com/processone/docker-ejabberd)
    # # Do not work reliably
    # build:
    #   context: ./docker-ejabberd/ecs
    #   args:
    #     VERSION: "latest"

    image: ejabberd/ecs

    # environment:
      # - ERLANG_NODE_ARG=ejabberd@main
      # - ERLANG_COOKIE=dummycookie123
      # - CTL_ON_CREATE=register admin localhost asd
      # - CTL_ON_START=stats registeredusers ; status
    ports:
      - "5222:5222" # The default port for XMPP clients.
      - "5269:5269" # For XMPP federation. Only needed if you want to communicate with users on other servers.
      - "5280:5280" # For admin interface.
      - "5443:5443" # With encryption, used for admin interface, API, CAPTCHA, OAuth, Websockets and XMPP BOSH.
                    # 1883: Used for MQTT
                    # 4369-4399: EPMD and Erlang connectivity, used for ejabberdctl and clustering
    networks:
      - ejabberd
    volumes:
      # - ./.data/ejabberd/conf:/home/ejabberd/conf/
      - './ejabberd.yml:/home/ejabberd/conf/ejabberd.yml:ro'
      - ./.data/ejabberd/logs:/home/ejabberd/logs/
      - ./.data/ejabberd/upload:/home/ejabberd/upload/
      - ./.data/ejabberd/database:/home/ejabberd/database/
    healthcheck:
      test: netstat -nl | grep -q 5222
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 120
    restart: always

networks:
  ejabberd:
    external: false