version: "3"

services:
  gitea:
    container_name: gitea

    # # Local build (from https://github.com/go-gitea/gitea)
    # build:
    #   context: ./gitea
    #   args:
    #     GITEA_VERSION: "main" # or "v1.15.10

    image: gitea/gitea

    environment:
      - USER_UID=1000
      - USER_GID=1000
    ports:
      - "3000:3000"
      - "222:22"
    networks:
      - gitea
    volumes:
      - ./.data/gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    restart: always

networks:
  gitea:
    external: false