version: "3.4"

services:
  prosody:
    container_name: prosody

    # # Local build (from https://github.com/prosody/prosody-docker)
    # # Not reproducible
    # build:
    #   context: ./prosody-docker

    image: prosody/prosody

    # environment:
    #   # Auto user creation
    #   - LOCAL=admin
    #   - DOMAIN=localhost
    #   - PASSWORD=password
    ports:
      # - "80:80"
      - "5222:5222" # The default port for XMPP clients.
      - "5269:5269" # For XMPP federation. Only needed if you want to communicate with users on other servers.
      - "5347:5347" # XMPP component port
      - "5280:5280" # For admin interface.  BOSH / websocket port
      - "5281:5281" # Secure BOSH / websocket port
      - "5000:5000" # Proxy
    networks:
      - prosody
    volumes:
      - ./prosody.cfg.lua:/etc/prosody/prosody.cfg.lua:ro
      # - ./.data/prosody/conf:/etc/prosody
      - ./.data/prosody/certs:/etc/prosody/certs
      - ./.data/prosody/logs:/var/log/prosody
      - ./.data/prosody/modules:/usr/lib/prosody-modules
      - ./.data/prosody/data:/var/lib/prosody
      - ./.data/letsencrypt:/etc/letsencrypt
    restart: always

  coturn:
    container_name: coturn

    # # Local build (from https://github.com/coturn/coturn)
    # # Not reproducible
    # build:
    #   context: ./coturn/docker/coturn/alpine

    image: coturn/coturn

    ports:
      - "3478:3478"
      - "3478:3478/udp"
      - "5349:5349"
      - "5349:5349/udp"
      - "49152-49280:49152-49280/udp"
    networks:
      - prosody
    volumes:
      - ./coturn.conf:/etc/coturn/turnserver.conf:ro
    restart: always

networks:
  prosody:
    external: false