version: '2'
services:
  openvpn:
    container_name: openvpn

    # # Local build (from https://github.com/kylemanna/docker-openvpn)
    # build:
    #   context: ./docker-openvpn

    image: kylemanna/openvpn

    cap_add:
      - NET_ADMIN
    ports:
      - "1194:1194/udp"
    networks:
      - openvpn
    volumes:
      - ./.data:/etc/openvpn
    restart: always

networks:
  openvpn:
    external: false